Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - spec/cypress/**/*
    - config/initializers/money.rb
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
Style/StringLiterals:
  Exclude:
    - config/spring.rb
    - config/application.rb
    - config/puma.rb
    - config/environments/production.rb
    - config/initializers/active_admin.rb
    - app/admin/dashboard.rb
    - spec/rails_helper.rb
    - db/migrate/*
Style/HashSyntax:
  Exclude:
    - db/migrate/*
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/production.rb
Layout/EmptyLines:
  Exclude:
    - Gemfile
    - db/migrate/*
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/migrate/*
Lint/UnusedBlockArgument:
  Exclude:
    - Gemfile
Style/SymbolArray:
  Exclude:
    - Gemfile
    - config/initializers/active_admin.rb
Style/CommentedKeyword:
  Exclude:
    - app/admin/dashboard.rb
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
Metrics/BlockLength:
  Exclude:
    - app/admin/*
    - spec/**/*
Lint/AmbiguousOperator:
  Exclude:
    - app/admin/*
Style/SymbolArray:
  Exclude:
    - ./**/*
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/api/*
