default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: foobar
  password: password

development:
  <<: *default
  database: contact_manager_development

test:
  <<: *default
  database: contact_manager_test

production:
  <<: *default
  database: contact_manager_production

